# Generated by Django 4.2.6 on 2023-10-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_quantity',
            field=models.DecimalField(decimal_places=1, default=0, help_text='In KGs', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('Kaju Katri', 'Kaju Katri'), ('Magaj', 'Magaj'), ('Premium Mohanthal', 'Premium Mohanthal'), ('Special Toparapak', 'Special Toparapak'), ('Barfi', 'Barfi'), ('Mava Mix Mithai', 'Mava Mix Mithai'), ('Dry Fruite Biscuite', 'Dry Fruite Biscuite'), ('Surti Chavanu', 'Surti Chavanu'), ('Son Papdi', 'Son Papdi')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=1, default=0, help_text='In KGs', max_digits=10),
        ),
    ]
