# Generated by Django 4.2.6 on 2023-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options_remove_item_ordered_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
