# Generated by Django 4.2.6 on 2023-10-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_billbook_dealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillBook',
        ),
    ]
