# Generated by Django 4.2.6 on 2023-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_box_dispatched_1000_item_box_dispatched_500_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='dispatched',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
