# Generated by Django 4.2.6 on 2023-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_delivered_order_dispatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, verbose_name='Advanced Collected'),
        ),
    ]
