# Generated by Django 4.2.6 on 2023-11-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_dispatched_date_alter_order_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchModel',
            fields=[
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
    ]
