# Generated by Django 4.2.6 on 2023-10-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='books',
        ),
    ]
