# Generated by Django 4.2.6 on 2023-11-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_customuser_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount_received',
            field=models.IntegerField(default=0),
        ),
    ]
