# Generated by Django 4.2.6 on 2023-11-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_customuser_amount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
