# Generated by Django 4.2.6 on 2023-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_remove_customuser_amount_received_userdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeposit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
